---
server:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    password:
      continue-on-error: true
      hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 7190000
        maximumPoolSize: 50
        minimumIdle: 2
      initialization-mode: always
      initialize: true
    url: "jdbc:postgresql://localhost:5432/blogDB"
    username: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          criteria.literal_handling_mode: BIND
          jdbc.batch_size: 20
    show-sql: true
  port: 8080
  spring:
    profiles:
      active: default
      mvc:
        static-path-pattern: /resources/**

