server:
  port: 8080

  spring:
    profiles:
      active: default

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: create
#      ddl-auto: create-drop
      properties:
        hibernate:
          jdbc.batch_size: 20
          criteria.literal_handling_mode: BIND

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blogDB?serverTimezone=Europe/Moscow&useSSL=false
#      url: jdbc:h2:mem:localhost:5432/blogDB?serverTimezone=Europe/Moscow&useSSL=false;DB_CLOSE_ON_EXIT=FALSE
    username: postgres
    password:
      initialization-mode: always
      initialize: true
      continue-on-error: true
      hikari:
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 7190000
        minimumIdle: 2
        maximumPoolSize: 50




